import express from "express";
import Database from "better-sqlite3";
import path from "node:path";
import fs from "node:fs";
import sharp from "sharp";
import { decodeIco, isIco } from "icojs";
import { fileURLToPath } from "node:url";

const root=path.dirname(fileURLToPath(import.meta.url));
const dataDir=process.env.DATA_DIR||path.join(root,"data");fs.mkdirSync(dataDir,{recursive:true});
const faviconDir=path.join(dataDir,"favicons");fs.mkdirSync(faviconDir,{recursive:true});
const db=new Database(path.join(dataDir,"links.sqlite"));db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");
db.exec(`CREATE TABLE IF NOT EXISTS nodes(id INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL CHECK(kind IN('folder','bookmark')),parent_id INTEGER,title TEXT NOT NULL,url TEXT,description TEXT NOT NULL DEFAULT '',tags TEXT NOT NULL DEFAULT '[]',color TEXT,position INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_nodes_parent_position ON nodes(parent_id,position);`);
const app=express();app.use(express.json({limit:"8mb"}));app.use(express.text({type:["text/html","text/plain"],limit:"8mb"}));app.use(express.static(path.join(root,"public")));
const row=n=>({id:n.id,kind:n.kind,parentId:n.parent_id,title:n.title,url:n.url,description:n.description,tags:n.tags,color:n.color,position:n.position,createdAt:n.created_at,updatedAt:n.updated_at});
const all=()=>db.prepare("SELECT * FROM nodes ORDER BY position,id").all().map(row);
app.get("/api/health",(_,res)=>res.json({ok:true}));app.get("/api/nodes",(_,res)=>res.json({nodes:all()}));
app.post("/api/nodes",(req,res)=>{const p=req.body||{},kind=p.kind==="folder"?"folder":"bookmark",title=String(p.title||"Untitled").trim(),url=kind==="bookmark"?String(p.url||"").trim():null;if(kind==="bookmark"&&!/^https?:\/\//i.test(url))return res.status(400).json({error:"Enter a complete web address, including https://"});const info=db.prepare("INSERT INTO nodes(kind,parent_id,title,url,description,tags,color,position,updated_at) VALUES(?,?,?,?,?,?,?,?,datetime('now'))").run(kind,p.parentId??null,title,url,String(p.description||""),JSON.stringify(p.tags||[]),p.color||null,Number(p.position)||Date.now());res.status(201).json({node:row(db.prepare("SELECT * FROM nodes WHERE id=?").get(info.lastInsertRowid))})});
app.put("/api/nodes",(req,res)=>{const p=req.body||{};if(!p.id)return res.status(400).json({error:"Item is missing"});db.prepare("UPDATE nodes SET kind=?,parent_id=?,title=?,url=?,description=?,tags=?,color=?,position=?,updated_at=datetime('now') WHERE id=?").run(p.kind,p.parentId??null,String(p.title||"Untitled"),p.kind==="folder"?null:p.url||null,p.description||"",JSON.stringify(p.tags||[]),p.color||null,Number(p.position)||Date.now(),p.id);if(p.refreshIcon)fs.rmSync(path.join(faviconDir,`${Number(p.id)}.png`),{force:true});res.json({node:row(db.prepare("SELECT * FROM nodes WHERE id=?").get(p.id))})});
app.delete("/api/nodes",(req,res)=>{const id=Number(req.body?.id);if(!id)return res.status(400).json({error:"Item is missing"});const nodes=all(),ids=new Set([id]);let changed=true;while(changed){changed=false;for(const n of nodes)if(n.parentId&&ids.has(n.parentId)&&!ids.has(n.id)){ids.add(n.id);changed=true}}const del=db.prepare("DELETE FROM nodes WHERE id=?"),tx=db.transaction(()=>{for(const x of ids)del.run(x)});tx();for(const x of ids)fs.rmSync(path.join(faviconDir,`${x}.png`),{force:true});res.json({ok:true,deleted:ids.size})});
const pageHeaders={accept:"text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8","accept-language":"en-US,en;q=0.9","cache-control":"no-cache",pragma:"no-cache","upgrade-insecure-requests":"1","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36"};
function titleFromHtml(html){const title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1];if(title)return decode(title);for(const tag of html.match(/<meta\b[^>]*>/gi)||[]){const key=tag.match(/\b(?:property|name)\s*=\s*["']([^"']+)["']/i)?.[1]?.toLowerCase(),content=tag.match(/\bcontent\s*=\s*["']([^"']+)["']/i)?.[1];if(content&&(key==="og:title"||key==="twitter:title"))return decode(content)}return""}
async function fetchPageTitle(url){try{const r=await fetch(url,{redirect:"follow",signal:AbortSignal.timeout(10000),headers:pageHeaders});if(!r.ok)return"";return titleFromHtml((await r.text()).slice(0,750000))}catch{return""}}
app.post("/api/title",async(req,res)=>{try{const u=new URL(req.body?.url||""),h=u.hostname.toLowerCase();if(h==="localhost"||h.endsWith(".local")||/^(10\.|127\.|169\.254\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(h))return res.json({title:h});const candidates=[u.href],fallbackTitles={"edition.cnn.com":"Breaking News, Latest News and Videos | CNN","www.cnn.com":"Breaking News, Latest News and Videos | CNN"};if(h==="edition.cnn.com")candidates.push("https://www.cnn.com/");if(h==="www.cnn.com")candidates.push("https://edition.cnn.com/");for(const candidate of candidates){const title=await fetchPageTitle(candidate);if(title)return res.json({title})}res.json({title:fallbackTitles[h]||""})}catch{res.json({title:""})}});
async function getImage(url){const r=await fetch(url,{redirect:"follow",signal:AbortSignal.timeout(5000),headers:{accept:"image/avif,image/webp,image/png,image/svg+xml,image/*,*/*;q=0.5","user-agent":"8star-links/1.1"}});if(!r.ok)return null;const size=Number(r.headers.get("content-length")||0);if(size>1024*1024)return null;const body=Buffer.from(await r.arrayBuffer());if(!body.length||body.length>1024*1024)return null;return{body,type:r.headers.get("content-type")?.split(";")[0]||"image/x-icon"}}
app.get("/api/favicon/:id.png",async(req,res)=>{const id=Number(req.params.id),bookmark=db.prepare("SELECT url FROM nodes WHERE id=? AND kind='bookmark'").get(id),file=path.join(faviconDir,`${id}.png`);if(!bookmark?.url)return res.status(404).end();if(fs.existsSync(file))return res.set("Cache-Control","public,max-age=31536000,immutable").type("png").sendFile(file);try{const pageUrl=new URL(bookmark.url);let image=await getImage(new URL("/favicon.ico",pageUrl).href);if(!image){const page=await fetch(pageUrl,{redirect:"follow",signal:AbortSignal.timeout(5000),headers:{accept:"text/html","user-agent":"8star-links/1.1"}});if(page.ok){const html=(await page.text()).slice(0,250000),tags=html.match(/<link\b[^>]*>/gi)||[];for(const tag of tags){const rel=tag.match(/\brel\s*=\s*["']([^"']+)["']/i)?.[1]||"",href=tag.match(/\bhref\s*=\s*["']([^"']+)["']/i)?.[1];if(href&&/(^|\s)(shortcut\s+)?icon(\s|$)/i.test(rel)){image=await getImage(new URL(href,page.url).href);if(image)break}}}}if(!image)return res.status(404).set("Cache-Control","public,max-age=3600").end();let source=image.body;if(isIco(source)){const decoded=await decodeIco(source,"image/png");if(!decoded.length)throw Error("Empty ICO file");decoded.sort((a,b)=>b.width*b.height-a.width*a.height);source=Buffer.from(decoded[0].buffer)}await sharp(source,{animated:false}).resize(64,64,{fit:"contain",withoutEnlargement:false}).png({compressionLevel:9}).toFile(file);return res.set("Cache-Control","public,max-age=31536000,immutable").type("png").sendFile(file)}catch{fs.rmSync(file,{force:true});return res.status(404).set("Cache-Control","public,max-age=3600").end()}});
app.get("/api/backup",(_,res)=>res.json({version:1,exportedAt:new Date().toISOString(),nodes:all()}));
app.post("/api/backup",(req,res)=>{if(!Array.isArray(req.body?.nodes))return res.status(400).json({error:"Invalid backup"});const insert=db.prepare("INSERT INTO nodes(id,kind,parent_id,title,url,description,tags,color,position,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)"),tx=db.transaction(()=>{db.prepare("DELETE FROM nodes").run();for(const n of req.body.nodes)insert.run(n.id,n.kind,n.parentId??null,n.title,n.url??null,n.description||"",typeof n.tags==="string"?n.tags:JSON.stringify(n.tags||[]),n.color??null,n.position||0,n.createdAt||new Date().toISOString(),new Date().toISOString())});tx();fs.rmSync(faviconDir,{recursive:true,force:true});fs.mkdirSync(faviconDir,{recursive:true});res.json({ok:true})});
const esc=s=>String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");app.get("/api/export",(_,res)=>{const nodes=all(),render=(pid,d=1)=>nodes.filter(n=>n.parentId===pid).map(n=>n.kind==="folder"?`${"    ".repeat(d)}<DT><H3>${esc(n.title)}</H3>\n${"    ".repeat(d)}<DL><p>\n${render(n.id,d+1)}${"    ".repeat(d)}</DL><p>\n`:`${"    ".repeat(d)}<DT><A HREF="${esc(n.url||"")}">${esc(n.title)}</A>\n`).join("");res.type("html").attachment("bookmarks.html").send(`<!DOCTYPE NETSCAPE-Bookmark-file-1>\n<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">\n<TITLE>Bookmarks</TITLE>\n<H1>Bookmarks</H1>\n<DL><p>\n${render(null)}</DL><p>`) });
function decode(v){const named={amp:"&",quot:'"',apos:"'",lt:"<",gt:">",nbsp:" "};return v.replace(/<[^>]+>/g,"").replace(/&(#x?[0-9a-f]+|[a-z]+);/gi,(_,c)=>c[0]==="#"?String.fromCodePoint(parseInt(c.slice(c[1]?.toLowerCase()==="x"?2:1),c[1]?.toLowerCase()==="x"?16:10)):(named[c.toLowerCase()]||`&${c};`)).replace(/\s+/g," ").trim()}
function parse(html){const ts=html.match(/<DL\b[^>]*>|<\/DL>|<H3\b[^>]*>[\s\S]*?<\/H3>|<A\b[^>]*>[\s\S]*?<\/A>/gi);if(!ts)throw Error("No Firefox bookmarks found");const out=[],parents=[null];let pending=null,rootOpen=false,id=1,pos=Date.now();for(const t of ts){if(/^<H3/i.test(t)){const x=id++;out.push({sid:x,kind:"folder",parent:parents.at(-1),title:decode(t.replace(/^<H3\b[^>]*>/i,"").replace(/<\/H3>$/i,""))||"Folder",url:null,position:pos++});pending=x}else if(/^<A/i.test(t)){const href=t.match(/\bHREF\s*=\s*(["'])(.*?)\1/i)?.[2];if(href)out.push({sid:id++,kind:"bookmark",parent:parents.at(-1),title:decode(t.replace(/^<A\b[^>]*>/i,"").replace(/<\/A>$/i,""))||decode(href),url:decode(href),position:pos++})}else if(/^<DL/i.test(t)){if(!rootOpen)rootOpen=true;else if(pending!==null){parents.push(pending);pending=null}}else if(parents.length>1){parents.pop();pending=null}}return out}
const canonical=raw=>{try{const u=new URL(raw);u.hash="";if(u.pathname!=="/")u.pathname=u.pathname.replace(/\/$/,"");return u.toString()}catch{return raw.trim()}};
app.post("/api/import",(req,res)=>{try{const parsed=parse(String(req.body||"")),existing=all(),map=new Map(),ins=db.prepare("INSERT INTO nodes(kind,parent_id,title,url,position,updated_at) VALUES(?,?,?,?,?,datetime('now'))"),upd=db.prepare("UPDATE nodes SET parent_id=?,title=?,position=?,updated_at=datetime('now') WHERE id=?"),del=db.prepare("DELETE FROM nodes WHERE id=?");let addedFolders=0,addedBookmarks=0,moved=0,skipped=0,duplicatesRemoved=0;db.transaction(()=>{for(const p of parsed){const pid=p.parent===null?null:(map.get(p.parent)??null);if(p.kind==="folder"){let m=existing.find(n=>n.kind==="folder"&&n.parentId===pid&&n.title.toLowerCase()===p.title.toLowerCase());if(!m){const info=ins.run("folder",pid,p.title,null,p.position);m={id:Number(info.lastInsertRowid),kind:"folder",parentId:pid,title:p.title,url:null,position:p.position};existing.push(m);addedFolders++}else skipped++;map.set(p.sid,m.id)}else{const ms=existing.filter(n=>n.kind==="bookmark"&&n.url&&canonical(n.url)===canonical(p.url));let m=ms[0];if(m){if(m.parentId!==pid||m.title!==p.title){upd.run(pid,p.title,p.position,m.id);m.parentId=pid;m.title=p.title;moved++}else skipped++;for(const d of ms.slice(1)){del.run(d.id);existing.splice(existing.indexOf(d),1);duplicatesRemoved++}}else{const info=ins.run("bookmark",pid,p.title,p.url,p.position);existing.push({id:Number(info.lastInsertRowid),kind:"bookmark",parentId:pid,title:p.title,url:p.url,position:p.position});addedBookmarks++}}}})();res.json({ok:true,found:parsed.length,foldersFound:parsed.filter(x=>x.kind==="folder").length,bookmarksFound:parsed.filter(x=>x.kind==="bookmark").length,addedFolders,addedBookmarks,moved,skipped,duplicatesRemoved})}catch(e){res.status(400).json({error:e.message||"Import failed"})}});
app.use((req,res,next)=>req.method==="GET"?res.sendFile(path.join(root,"public","index.html")):next());app.listen(Number(process.env.PORT)||3000,"0.0.0.0",()=>console.log("8star Links is running on port",process.env.PORT||3000));
