import express from "express";
import Database from "better-sqlite3";
import path from "node:path";
import fs from "node:fs";
import { fileURLToPath } from "node:url";

const root=path.dirname(fileURLToPath(import.meta.url));
const dataDir=process.env.DATA_DIR||path.join(root,"data");fs.mkdirSync(dataDir,{recursive:true});
const db=new Database(path.join(dataDir,"links.sqlite"));db.pragma("journal_mode = WAL");db.pragma("foreign_keys = ON");
db.exec(`CREATE TABLE IF NOT EXISTS nodes(id INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL CHECK(kind IN('folder','bookmark')),parent_id INTEGER,title TEXT NOT NULL,url TEXT,description TEXT NOT NULL DEFAULT '',tags TEXT NOT NULL DEFAULT '[]',color TEXT,position INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX IF NOT EXISTS idx_nodes_parent_position ON nodes(parent_id,position);`);
const app=express();app.use(express.json({limit:"8mb"}));app.use(express.text({type:["text/html","text/plain"],limit:"8mb"}));app.use(express.static(path.join(root,"public")));
const row=n=>({id:n.id,kind:n.kind,parentId:n.parent_id,title:n.title,url:n.url,description:n.description,tags:n.tags,color:n.color,position:n.position,createdAt:n.created_at,updatedAt:n.updated_at});
const all=()=>db.prepare("SELECT * FROM nodes ORDER BY position,id").all().map(row);
app.get("/api/health",(_,res)=>res.json({ok:true}));app.get("/api/nodes",(_,res)=>res.json({nodes:all()}));
app.post("/api/nodes",(req,res)=>{const p=req.body||{},kind=p.kind==="folder"?"folder":"bookmark",title=String(p.title||"Naamloos").trim(),url=kind==="bookmark"?String(p.url||"").trim():null;if(kind==="bookmark"&&!/^https?:\/\//i.test(url))return res.status(400).json({error:"Gebruik een volledig webadres, inclusief https://"});const info=db.prepare("INSERT INTO nodes(kind,parent_id,title,url,description,tags,color,position,updated_at) VALUES(?,?,?,?,?,?,?,?,datetime('now'))").run(kind,p.parentId??null,title,url,String(p.description||""),JSON.stringify(p.tags||[]),p.color||null,Number(p.position)||Date.now());res.status(201).json({node:row(db.prepare("SELECT * FROM nodes WHERE id=?").get(info.lastInsertRowid))})});
app.put("/api/nodes",(req,res)=>{const p=req.body||{};if(!p.id)return res.status(400).json({error:"Item ontbreekt"});db.prepare("UPDATE nodes SET kind=?,parent_id=?,title=?,url=?,description=?,tags=?,color=?,position=?,updated_at=datetime('now') WHERE id=?").run(p.kind,p.parentId??null,String(p.title||"Naamloos"),p.kind==="folder"?null:p.url||null,p.description||"",JSON.stringify(p.tags||[]),p.color||null,Number(p.position)||Date.now(),p.id);res.json({node:row(db.prepare("SELECT * FROM nodes WHERE id=?").get(p.id))})});
app.delete("/api/nodes",(req,res)=>{const id=Number(req.body?.id);if(!id)return res.status(400).json({error:"Item ontbreekt"});const nodes=all(),ids=new Set([id]);let changed=true;while(changed){changed=false;for(const n of nodes)if(n.parentId&&ids.has(n.parentId)&&!ids.has(n.id)){ids.add(n.id);changed=true}}const del=db.prepare("DELETE FROM nodes WHERE id=?"),tx=db.transaction(()=>{for(const x of ids)del.run(x)});tx();res.json({ok:true,deleted:ids.size})});
app.post("/api/title",async(req,res)=>{try{const u=new URL(req.body?.url||""),h=u.hostname.toLowerCase();if(h==="localhost"||h.endsWith(".local")||/^(10\.|127\.|169\.254\.|192\.168\.|172\.(1[6-9]|2\d|3[01])\.)/.test(h))return res.json({title:h});const r=await fetch(u,{redirect:"follow",signal:AbortSignal.timeout(5000),headers:{"user-agent":"8star-links/1.0"}}),html=(await r.text()).slice(0,250000),m=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);res.json({title:(m?.[1]||h).replace(/\s+/g," ").replace(/&amp;/g,"&").trim()})}catch{res.json({title:""})}});
app.get("/api/backup",(_,res)=>res.json({version:1,exportedAt:new Date().toISOString(),nodes:all()}));
app.post("/api/backup",(req,res)=>{if(!Array.isArray(req.body?.nodes))return res.status(400).json({error:"Ongeldige back-up"});const insert=db.prepare("INSERT INTO nodes(id,kind,parent_id,title,url,description,tags,color,position,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)"),tx=db.transaction(()=>{db.prepare("DELETE FROM nodes").run();for(const n of req.body.nodes)insert.run(n.id,n.kind,n.parentId??null,n.title,n.url??null,n.description||"",typeof n.tags==="string"?n.tags:JSON.stringify(n.tags||[]),n.color??null,n.position||0,n.createdAt||new Date().toISOString(),new Date().toISOString())});tx();res.json({ok:true})});
const esc=s=>String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;");app.get("/api/export",(_,res)=>{const nodes=all(),render=(pid,d=1)=>nodes.filter(n=>n.parentId===pid).map(n=>n.kind==="folder"?`${"    ".repeat(d)}<DT><H3>${esc(n.title)}</H3>\n${"    ".repeat(d)}<DL><p>\n${render(n.id,d+1)}${"    ".repeat(d)}</DL><p>\n`:`${"    ".repeat(d)}<DT><A HREF="${esc(n.url||"")}">${esc(n.title)}</A>\n`).join("");res.type("html").attachment("bookmarks.html").send(`<!DOCTYPE NETSCAPE-Bookmark-file-1>\n<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=UTF-8">\n<TITLE>Bookmarks</TITLE>\n<H1>Bookmarks</H1>\n<DL><p>\n${render(null)}</DL><p>`) });
function decode(v){const named={amp:"&",quot:'"',apos:"'",lt:"<",gt:">",nbsp:" "};return v.replace(/<[^>]+>/g,"").replace(/&(#x?[0-9a-f]+|[a-z]+);/gi,(_,c)=>c[0]==="#"?String.fromCodePoint(parseInt(c.slice(c[1]?.toLowerCase()==="x"?2:1),c[1]?.toLowerCase()==="x"?16:10)):(named[c.toLowerCase()]||`&${c};`)).replace(/\s+/g," ").trim()}
function parse(html){const ts=html.match(/<DL\b[^>]*>|<\/DL>|<H3\b[^>]*>[\s\S]*?<\/H3>|<A\b[^>]*>[\s\S]*?<\/A>/gi);if(!ts)throw Error("Geen Firefox-bookmarks gevonden");const out=[],parents=[null];let pending=null,rootOpen=false,id=1,pos=Date.now();for(const t of ts){if(/^<H3/i.test(t)){const x=id++;out.push({sid:x,kind:"folder",parent:parents.at(-1),title:decode(t.replace(/^<H3\b[^>]*>/i,"").replace(/<\/H3>$/i,""))||"Map",url:null,position:pos++});pending=x}else if(/^<A/i.test(t)){const href=t.match(/\bHREF\s*=\s*(["'])(.*?)\1/i)?.[2];if(href)out.push({sid:id++,kind:"bookmark",parent:parents.at(-1),title:decode(t.replace(/^<A\b[^>]*>/i,"").replace(/<\/A>$/i,""))||decode(href),url:decode(href),position:pos++})}else if(/^<DL/i.test(t)){if(!rootOpen)rootOpen=true;else if(pending!==null){parents.push(pending);pending=null}}else if(parents.length>1){parents.pop();pending=null}}return out}
const canonical=raw=>{try{const u=new URL(raw);u.hash="";if(u.pathname!=="/")u.pathname=u.pathname.replace(/\/$/,"");return u.toString()}catch{return raw.trim()}};
app.post("/api/import",(req,res)=>{try{const parsed=parse(String(req.body||"")),existing=all(),map=new Map(),ins=db.prepare("INSERT INTO nodes(kind,parent_id,title,url,position,updated_at) VALUES(?,?,?,?,?,datetime('now'))"),upd=db.prepare("UPDATE nodes SET parent_id=?,title=?,position=?,updated_at=datetime('now') WHERE id=?"),del=db.prepare("DELETE FROM nodes WHERE id=?");let addedFolders=0,addedBookmarks=0,moved=0,skipped=0,duplicatesRemoved=0;db.transaction(()=>{for(const p of parsed){const pid=p.parent===null?null:(map.get(p.parent)??null);if(p.kind==="folder"){let m=existing.find(n=>n.kind==="folder"&&n.parentId===pid&&n.title.toLowerCase()===p.title.toLowerCase());if(!m){const info=ins.run("folder",pid,p.title,null,p.position);m={id:Number(info.lastInsertRowid),kind:"folder",parentId:pid,title:p.title,url:null,position:p.position};existing.push(m);addedFolders++}else skipped++;map.set(p.sid,m.id)}else{const ms=existing.filter(n=>n.kind==="bookmark"&&n.url&&canonical(n.url)===canonical(p.url));let m=ms[0];if(m){if(m.parentId!==pid||m.title!==p.title){upd.run(pid,p.title,p.position,m.id);m.parentId=pid;m.title=p.title;moved++}else skipped++;for(const d of ms.slice(1)){del.run(d.id);existing.splice(existing.indexOf(d),1);duplicatesRemoved++}}else{const info=ins.run("bookmark",pid,p.title,p.url,p.position);existing.push({id:Number(info.lastInsertRowid),kind:"bookmark",parentId:pid,title:p.title,url:p.url,position:p.position});addedBookmarks++}}}})();res.json({ok:true,found:parsed.length,foldersFound:parsed.filter(x=>x.kind==="folder").length,bookmarksFound:parsed.filter(x=>x.kind==="bookmark").length,addedFolders,addedBookmarks,moved,skipped,duplicatesRemoved})}catch(e){res.status(400).json({error:e.message||"Importeren mislukt"})}});
app.use((req,res,next)=>req.method==="GET"?res.sendFile(path.join(root,"public","index.html")):next());app.listen(Number(process.env.PORT)||3000,"0.0.0.0",()=>console.log("8star Links draait op poort",process.env.PORT||3000));
